# Generated by Django 3.0.5 on 2020-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event name')),
                ('date', models.DateTimeField(verbose_name='Event date')),
                ('venue', models.CharField(max_length=120, verbose_name='Event venue')),
                ('manager', models.CharField(max_length=120, verbose_name='Event manager')),
                ('description', models.TextField(blank=True, verbose_name='Event description')),
            ],
        ),
    ]
